name: testing send mail

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: installing mail
        run: sudo apt install mailutils
      - name: checking mail
        run:  mail -V
      - name: sending mail
        run: mail -s 'temaprory mail' rahulgahalaut333@gmail.com <<< 'testing message body'
