
name:testing workflow
on:
  Workflow-dispach:
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name:sending mail
        run: |
          sudo apt install mailutils
          mail -V
          mail -s 'temaprory mail' rahulgahalaut333@gmail.com <<< 'testing message body'
